const BOOK_MAP: Record<string, string> = {
  genesis: 'GEN',
  gen: 'GEN',
  ge: 'GEN',
  gn: 'GEN',
  exodus: 'EXO',
  exo: 'EXO',
  ex: 'EXO',
  exod: 'EXO',
  leviticus: 'LEV',
  lev: 'LEV',
  le: 'LEV',
  lv: 'LEV',
  numbers: 'NUM',
  num: 'NUM',
  nu: 'NUM',
  nm: 'NUM',
  nb: 'NUM',
  deuteronomy: 'DEU',
  deu: 'DEU',
  deut: 'DEU',
  dt: 'DEU',
  de: 'DEU',
  joshua: 'JOS',
  jos: 'JOS',
  josh: 'JOS',
  jo: 'JOS',
  judges: 'JDG',
  jdg: 'JDG',
  judg: 'JDG',
  jg: 'JDG',
  ruth: 'RUT',
  rut: 'RUT',
  ru: 'RUT',
  '1samuel': '1SA',
  '1sam': '1SA',
  '1sa': '1SA',
  '1s': '1SA',
  'i samuel': '1SA',
  'i sam': '1SA',
  'first samuel': '1SA',
  '2samuel': '2SA',
  '2sam': '2SA',
  '2sa': '2SA',
  '2s': '2SA',
  'ii samuel': '2SA',
  'ii sam': '2SA',
  'second samuel': '2SA',
  '1kings': '1KI',
  '1kgs': '1KI',
  '1ki': '1KI',
  '1k': '1KI',
  'i kings': '1KI',
  'first kings': '1KI',
  '2kings': '2KI',
  '2kgs': '2KI',
  '2ki': '2KI',
  '2k': '2KI',
  'ii kings': '2KI',
  'second kings': '2KI',
  '1chronicles': '1CH',
  '1chr': '1CH',
  '1ch': '1CH',
  'i chronicles': '1CH',
  'first chronicles': '1CH',
  '2chronicles': '2CH',
  '2chr': '2CH',
  '2ch': '2CH',
  'ii chronicles': '2CH',
  'second chronicles': '2CH',
  ezra: 'EZR',
  ezr: 'EZR',
  nehemiah: 'NEH',
  neh: 'NEH',
  ne: 'NEH',
  esther: 'EST',
  est: 'EST',
  esth: 'EST',
  es: 'EST',
  job: 'JOB',
  jb: 'JOB',
  psalms: 'PSA',
  psalm: 'PSA',
  psa: 'PSA',
  ps: 'PSA',
  pss: 'PSA',
  proverbs: 'PRO',
  pro: 'PRO',
  prov: 'PRO',
  pr: 'PRO',
  prv: 'PRO',
  ecclesiastes: 'ECC',
  ecc: 'ECC',
  eccl: 'ECC',
  ec: 'ECC',
  qoh: 'ECC',
  'song of solomon': 'SNG',
  'song of songs': 'SNG',
  song: 'SNG',
  sng: 'SNG',
  ss: 'SNG',
  sos: 'SNG',
  isaiah: 'ISA',
  isa: 'ISA',
  is: 'ISA',
  jeremiah: 'JER',
  jer: 'JER',
  je: 'JER',
  jr: 'JER',
  lamentations: 'LAM',
  lam: 'LAM',
  la: 'LAM',
  ezekiel: 'EZK',
  ezk: 'EZK',
  ezek: 'EZK',
  eze: 'EZK',
  daniel: 'DAN',
  dan: 'DAN',
  da: 'DAN',
  dn: 'DAN',
  hosea: 'HOS',
  hos: 'HOS',
  ho: 'HOS',
  joel: 'JOL',
  jol: 'JOL',
  jl: 'JOL',
  amos: 'AMO',
  amo: 'AMO',
  am: 'AMO',
  obadiah: 'OBA',
  oba: 'OBA',
  ob: 'OBA',
  jonah: 'JON',
  jon: 'JON',
  jnh: 'JON',
  micah: 'MIC',
  mic: 'MIC',
  mi: 'MIC',
  nahum: 'NAH',
  nah: 'NAH',
  na: 'NAH',
  habakkuk: 'HAB',
  hab: 'HAB',
  hb: 'HAB',
  zephaniah: 'ZEP',
  zep: 'ZEP',
  zeph: 'ZEP',
  haggai: 'HAG',
  hag: 'HAG',
  hg: 'HAG',
  zechariah: 'ZEC',
  zec: 'ZEC',
  zech: 'ZEC',
  malachi: 'MAL',
  mal: 'MAL',
  ml: 'MAL',
  matthew: 'MAT',
  mat: 'MAT',
  matt: 'MAT',
  mt: 'MAT',
  mark: 'MRK',
  mrk: 'MRK',
  mk: 'MRK',
  mr: 'MRK',
  luke: 'LUK',
  luk: 'LUK',
  lk: 'LUK',
  lu: 'LUK',
  john: 'JHN',
  jhn: 'JHN',
  jn: 'JHN',
  joh: 'JHN',
  acts: 'ACT',
  act: 'ACT',
  ac: 'ACT',
  romans: 'ROM',
  rom: 'ROM',
  ro: 'ROM',
  rm: 'ROM',
  '1corinthians': '1CO',
  '1cor': '1CO',
  '1co': '1CO',
  '1c': '1CO',
  'i corinthians': '1CO',
  'first corinthians': '1CO',
  '2corinthians': '2CO',
  '2cor': '2CO',
  '2co': '2CO',
  '2c': '2CO',
  'ii corinthians': '2CO',
  'second corinthians': '2CO',
  galatians: 'GAL',
  gal: 'GAL',
  ga: 'GAL',
  gl: 'GAL',
  ephesians: 'EPH',
  eph: 'EPH',
  ep: 'EPH',
  philippians: 'PHP',
  php: 'PHP',
  phil: 'PHP',
  ph: 'PHP',
  colossians: 'COL',
  col: 'COL',
  co: 'COL',
  '1thessalonians': '1TH',
  '1thess': '1TH',
  '1th': '1TH',
  'i thessalonians': '1TH',
  'first thessalonians': '1TH',
  '2thessalonians': '2TH',
  '2thess': '2TH',
  '2th': '2TH',
  'ii thessalonians': '2TH',
  'second thessalonians': '2TH',
  '1timothy': '1TI',
  '1tim': '1TI',
  '1ti': '1TI',
  'i timothy': '1TI',
  'first timothy': '1TI',
  '2timothy': '2TI',
  '2tim': '2TI',
  '2ti': '2TI',
  'ii timothy': '2TI',
  'second timothy': '2TI',
  titus: 'TIT',
  tit: 'TIT',
  ti: 'TIT',
  philemon: 'PHM',
  phm: 'PHM',
  pm: 'PHM',
  phlm: 'PHM',
  hebrews: 'HEB',
  heb: 'HEB',
  james: 'JAS',
  jas: 'JAS',
  jm: 'JAS',
  '1peter': '1PE',
  '1pet': '1PE',
  '1pe': '1PE',
  '1pt': '1PE',
  'i peter': '1PE',
  'first peter': '1PE',
  '2peter': '2PE',
  '2pet': '2PE',
  '2pe': '2PE',
  '2pt': '2PE',
  'ii peter': '2PE',
  'second peter': '2PE',
  '1john': '1JO',
  '1jn': '1JO',
  '1jo': '1JO',
  'i john': '1JO',
  'first john': '1JO',
  '2john': '2JO',
  '2jn': '2JO',
  '2jo': '2JO',
  'ii john': '2JO',
  'second john': '2JO',
  '3john': '3JO',
  '3jn': '3JO',
  '3jo': '3JO',
  'iii john': '3JO',
  'third john': '3JO',
  jude: 'JUD',
  jud: 'JUD',
  jd: 'JUD',
  revelation: 'REV',
  rev: 'REV',
  re: 'REV',
  revelations: 'REV',
}

export interface ParsedRef {
  passageId: string
}

export class ScriptureParseError extends Error {}

export function parseScriptureRef(input: string): ParsedRef {
  const trimmed = input.trim()

  // Match: <book> <chapter>:<verse>[-<endVerse>]
  // Also support "1 John 3:16" style with leading number + space before book name
  const match = trimmed.match(
    /^(\d?\s*[a-zA-Z]+(?:\s+[a-zA-Z]+)*)\s+(\d+):(\d+)(?:\s*[-–]\s*(\d+))?$/,
  )

  if (!match) {
    throw new ScriptureParseError(
      `Could not parse "${input}". Use format "John 3:16" or "Psalm 23:1-4".`,
    )
  }

  const bookRaw = match[1].trim()
  const chapter = match[2]
  const startVerse = match[3]
  const endVerse = match[4]

  // Normalize: lowercase, collapse whitespace, remove internal spaces for numbered books
  const bookKey = bookRaw.toLowerCase().replace(/\s+/g, ' ').trim()

  // Try exact key first
  let bookCode = BOOK_MAP[bookKey]

  // Try without spaces (e.g., "1 john" -> "1john")
  if (!bookCode) {
    bookCode = BOOK_MAP[bookKey.replace(/\s/g, '')]
  }

  if (!bookCode) {
    throw new ScriptureParseError(`Unknown book "${bookRaw}". Check spelling and try again.`)
  }

  if (endVerse) {
    return { passageId: `${bookCode}.${chapter}.${startVerse}-${bookCode}.${chapter}.${endVerse}` }
  }

  return { passageId: `${bookCode}.${chapter}.${startVerse}` }
}
